version: "3"
services:
  obsidian-livesync-classroom:
    image: obsidian-livesync-classroom
    container_name: obsidian-livesync-classroom
    restart: always
    volumes:
      - ./dat:/usr/src/app/dat:rw
